### PR TITLE
Adding Poetry install and usage instructions to README

### PR DESCRIPTION
**Pull request by brian-dlee**

### CODE REVIEW

**Comment by ajtorres9** [comment]
I should have mentioned I added a [commitizen](https://github.com/commitizen/cz-cli) [config](https://github.com/commitizen/cz-conventional-changelog) to this project. It will help with releases later on down the road, by providing a consistent commit log for programs like [`semantic-release`](https://github.com/semantic-release/semantic-release). Sorry for the library vomit, but the gist is that `commitizen` provides structured commit messages so programs like `semantic-release` can read them and determine what the next version of the package should be, while at the same time generate a standardized changelog. You don't necessarily have to update your individual commits for this PR, you can perform a squash merge and change the description to something like:

```
docs(ai): add poetry install and usage instructions to readme
```

You can honestly do that with all of your future commits if you perfer, just update the sytax at the time of the merge. Your call! 😄

**Comment by brian-dlee** [comment]
Did I do it, right? 😆

**Comment by ajtorres9** [comment]
LOL! 😂 No, you did not.

**Comment by ajtorres9** [comment]
@all-contributors please add @brian-dlee for documentation

**Comment by ajtorres9** [comment]
@all-contributors please add @brian-dlee for documentation

**Comment by ajtorres9** [comment]
@all-contributors please add @ajtorres9 for review

**Pull request merged**
